name: tests

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      
      - name: Cache Clojure Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: cache-${{ hashFiles('**/deps.edn') }}
      
      - name: Setup Java
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: '17'
      
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@9.5
        with:
          cli: 1.11.1.1200
      
      - name: Run Unit tests
        run: clojure -M:test/all
